version: "3.1"

services:
  dulcina_pg:
    image: postgres:15.1
    container_name: dulcina_pg
    restart: always
    environment:
      POSTGRES_DB: dulcinadb
      POSTGRES_USER: udulcina
      POSTGRES_PASSWORD: secret1234
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432